prebuilts: sign everything with platform
AuroraServices:
java -jar /opt/android-sdk/build-tools/29.0.3/lib/apksigner.jar verify
--verbose AuroraServices.apk
DOES NOT VERIFY
ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the
APK is signed using APK Signature Scheme v2 but no such signature was
found. Signature stripped?

FDroidPrivilegedExtension:
java -jar /opt/android-sdk/build-tools/29.0.3/lib/apksigner.jar verify
--verbose FDroidPrivilegedExtension.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): false
Verified using v3 scheme (APK Signature Scheme v3): false
Number of signers: 1

Both of these have signing issues: one isn't properly signed, the other is using v1 which has known vulnerabilities

Yes this will prevent users from updating these apps themselves but it's the only way to ensure security

Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>